name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install . pytest flake8

      - name: Lint
        run: flake8 src

      - name: Run tests
        env:
          PYTHONPATH: src
        run: pytest --maxfail=1 --disable-warnings -q

